import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#e2dfff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "inverse-surface": "#213145",
        "on-primary-fixed": "#002114",
        "primary-fixed-dim": "#68dba9",
        "primary-fixed": "#85f8c4",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "surface-bright": "#f8f9ff",
        "on-surface-variant": "#3d4a42",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed-variant": "#3a485c",
        "on-secondary-container": "#57657b",
        "outline": "#6d7a72",
        "on-secondary-fixed": "#0d1c2f",
        "surface": "#f8f9ff",
        "on-primary-container": "#f5fff7",
        "surface-variant": "#d3e4fe",
        "surface-container-low": "#eff4ff",
        "surface-container-high": "#dce9ff",
        "on-surface": "#0b1c30",
        "tertiary": "#4b41e1",
        "on-primary-fixed-variant": "#005137",
        "on-error-container": "#93000a",
        "surface-dim": "#cbdbf5",
        "tertiary-container": "#645efb",
        "error": "#ba1a1a",
        "secondary": "#515f74",
        "inverse-primary": "#68dba9",
        "primary-container": "#00855d",
        "surface-container": "#e5eeff",
        "tertiary-fixed-dim": "#c3c0ff",
        "secondary-fixed-dim": "#b9c7e0",
        "surface-tint": "#006c4a",
        "error-container": "#ffdad6",
        "secondary-container": "#d5e3fd",
        "primary": "#006948",
        "secondary-fixed": "#d5e3fd",
        "on-secondary": "#ffffff",
        "outline-variant": "#bccac0",
        "on-tertiary-fixed": "#0f0069",
        "on-background": "#0b1c30",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-fixed-variant": "#3323cc",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-2xl": "3rem",
        "space-sm": "0.5rem",
        "gutter-sm": "1rem",
        "gutter": "1.5rem",
        "space-xl": "2rem",
        "margin": "2rem",
        "margin-mobile": "1rem",
        "space-md": "1rem",
        "gutter-lg": "2rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "body-md": ["var(--font-inter)"],
        "display-lg": ["var(--font-plus-jakarta)"],
        "body-sm": ["var(--font-inter)"],
        "label-sm": ["var(--font-inter)"],
        "tabular-mono": ["var(--font-inter)"],
        "headline-sm": ["var(--font-plus-jakarta)"],
        "body-lg": ["var(--font-inter)"],
        "headline-xl-mobile": ["var(--font-plus-jakarta)"],
        "display-lg-mobile": ["var(--font-plus-jakarta)"],
        "label-md": ["var(--font-inter)"],
        "headline-xl": ["var(--font-plus-jakarta)"]
      },
      fontSize: {
        "body-md": ["0.9375rem", { "lineHeight": "1.5rem", "fontWeight": "400" }],
        "display-lg": ["3.25rem", { "lineHeight": "3.75rem", "letterSpacing": "-0.025em", "fontWeight": "700" }],
        "body-sm": ["0.8125rem", { "lineHeight": "1.25rem", "fontWeight": "400" }],
        "label-sm": ["0.75rem", { "lineHeight": "1rem", "letterSpacing": "0.025em", "fontWeight": "600" }],
        "tabular-mono": ["0.9375rem", { "lineHeight": "1.5rem", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "headline-sm": ["1.25rem", { "lineHeight": "1.75rem", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["1.125rem", { "lineHeight": "1.75rem", "fontWeight": "400" }],
        "headline-xl-mobile": ["1.625rem", { "lineHeight": "2rem", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "display-lg-mobile": ["2.25rem", { "lineHeight": "2.75rem", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["0.875rem", { "lineHeight": "1.25rem", "fontWeight": "500" }],
        "headline-xl": ["2rem", { "lineHeight": "2.5rem", "letterSpacing": "-0.02em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
};
export default config;
